package com.open.bomberman;

public enum AnimationKind {
	BOMB, FIRE_UP, FIRE_DOWN, FIRE_LEFT, FIRE_RIGHT, FIRE_VERT, FIRE_HORZ, FIRE_CENTER, FIRE_OBJECT, WALL, FIRE_WALL, KILL, BONUS_BOMB, BONUS_FIRE, BONUS_ROLLER

}
